--- 
- name: Install Docker, Docker-Compose, Jenkins Agent
  hosts: all
  become: yes

  
  tasks:
  
  #- name: Updating packages
  #  apt: upgrade=yes update_cache=true
  
  - name: Docker install
    apt: pkg=docker state=present
    #notify:
    #  - start docker
  
  - name: Docker-Compose install
    apt: pkg=docker-compose state=present

  - name: Java install
    apt: pkg=openjdk-8-jre state=present
    
  - name: Git install
    apt: pkg=git state=present update_cache=true
    #notify:
    #  - start git
    
  - name: Starting Docker service
    service: docker
    status: started
    
  - name: Starting Git service
    service: git
    status: started    
  
  - name: Getting Git Repository for Web Server
    shell: git clone https://github.com/krusty408/webserver
    
  - name: Changing Directory
    shell: cd /home/ubuntu/webserver
    
  - name: Running Docker-Compose file
    shell: ll
