---
- name: Install Docker, Docker-Compose, Jenkins Agent
  hosts: all
  become: yes

  
  tasks:
  - name: Install Docker
    apt: pkg=docker state=present
    notify:
      - start docker
  
  - name: Install Docker-Compose
    apt: pkg=docker-compose state=present update_cache=true
    # -name: Install Docker-Compose
   # yum: name=docker-compose state=latest   

    # - name: Start Docker and enabe it after  every boot
    #service: name=docker state=started enabled=yes
