---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    become: yes
    
    
- name: Install Docker, Docker-Compose, Jenkins Agent
  hosts: all
  become: yes

  
  tasks:
  - name: Docker install
    apt: pkg=docker state=present
    notify:
      - start docker
  
  - name: Docker-Compose install
    apt: pkg=docker-compose state=present

  - name: Java install
    apt: pkg=openjdk-8-jre state=present update_cache=true
